name: Deploy DEV site to Hetzner

on:
  workflow_dispatch:
  push:
    branches:
      - dev

concurrency:
  group: deploy-dev-hetzner
  cancel-in-progress: true

jobs:
  deploy-site-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: dev

      - name: Prepare site files
        run: |
          mkdir -p .deploy-site
          cp index.html .deploy-site/
          cp app.js .deploy-site/
          cp style.css .deploy-site/
          cp series.json .deploy-site/
          cp impressum-datenschutz.html .deploy-site/

          cp -R favicon_io .deploy-site/

      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Upload DEV site files
        env:
          HETZNER_HOST: ${{ secrets.HETZNER_HOST }}
          HETZNER_USER: ${{ secrets.HETZNER_USER }}
          HETZNER_PASSWORD: ${{ secrets.HETZNER_PASSWORD }}
          HETZNER_PORT: ${{ secrets.HETZNER_PORT }}
        run: |
          lftp -u "$HETZNER_USER","$HETZNER_PASSWORD" -p "$HETZNER_PORT" "sftp://$HETZNER_HOST" <<EOF
          set sftp:auto-confirm yes
          mirror -R .deploy-site ./rcracemap-dev --verbose --transfer-all
          bye
          EOF
